/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.44
 * Generated at: 2021-06-07 11:54:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.funding;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class fundingList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1622798345519L));
    _jspx_dependants.put("jar:file:/C:/Users/rojoo/git/interact_funding/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Users/rojoo/git/interact_funding/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Users/rojoo/git/interact_funding/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("이프", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/fundingList.css\" />\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("    $(function(){\r\n");
      out.write("        $(\"img[alt=image1]\").attr(\"src\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/food3.jpg\");\r\n");
      out.write("        $(\"img[alt=image2]\").attr(\"src\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/food2.jpg\");\r\n");
      out.write("        $(\"img[alt=image3]\").attr(\"src\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/food1.jpg\");\r\n");
      out.write("        $(\"img[alt=image4]\").attr(\"src\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/trip.jpg\");\r\n");
      out.write("        $(\"img[alt=image5]\").attr(\"src\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/game.jpg\");\r\n");
      out.write("    });\r\n");
      out.write("    $(function(){\r\n");
      out.write("        $(\".FundingProjectCardItem\").slice(0,3).show();\r\n");
      out.write("        $(\"#moreBtn\").click(function(e){\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t$(\".FundingProjectCardItem:hidden\").slice(0,3).show();\r\n");
      out.write("\t\t\tif($(\".FundingProjectCardItem:hidden\").length == 0){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("        })\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write(".slide-title{\r\n");
      out.write("   \tdisplay: block;\r\n");
      out.write("   \tposition: absolute;\r\n");
      out.write("   \tbottom: 20px;\r\n");
      out.write("   \tleft: 20px;\r\n");
      out.write("   \ttext-decoration: none;\r\n");
      out.write("   \toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write(".slide-title span{\r\n");
      out.write("   \tcolor: white;\r\n");
      out.write("   \tfont-size: 20px;\r\n");
      out.write("   \tfont-weight: 700;\r\n");
      out.write("}\r\n");
      out.write(".slide-title p{\r\n");
      out.write("   \tdisplay: block;\r\n");
      out.write("   \tcolor: white;\r\n");
      out.write("   \toverflow: hidden;\r\n");
      out.write("   \ttext-overflow: ellipsis;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<div class=\"FundingMainWrapper\">\r\n");
      out.write("       <div id=\"demo\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("           <ul class=\"carousel-indicators\">\r\n");
      out.write("               <li data-target=\"#demo\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("               <li data-target=\"#demo\" data-slide-to=\"1\"></li>\r\n");
      out.write("               <li data-target=\"#demo\" data-slide-to=\"2\"></li>\r\n");
      out.write("               <li data-target=\"#demo\" data-slide-to=\"3\"></li>\r\n");
      out.write("               <li data-target=\"#demo\" data-slide-to=\"4\"></li>\r\n");
      out.write("           </ul>\r\n");
      out.write("\r\n");
      out.write("           <div class=\"carousel-inner\">\r\n");
      out.write("               <div class=\"carousel-item active\">\r\n");
      out.write("                   <a href=\"#\">\r\n");
      out.write("                       <img alt=\"image1\" style=\"width: 1300px; height: 400px;\">\r\n");
      out.write("                    <div class=\"slide-title\">\r\n");
      out.write("                     <span>고급 고기</span>\r\n");
      out.write("                     <p>영양도 맛도 풍부한 갈비명가 갈비집이 만듭니다!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"carousel-item\">\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                    <img alt=\"image2\" style=\"width: 1300px; height: 400px;\">\r\n");
      out.write("                    <div class=\"slide-title\">\r\n");
      out.write("                    \t<span>한상차린 밥상! 한식매니아를 위한 밥상!</span>\r\n");
      out.write("                    \t<p>밥힘으로 삽니다.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"carousel-item\">\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                    <img alt=\"image3\" style=\"width: 1300px; height: 400px;\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"carousel-item\">\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                    <img alt=\"image4\" style=\"width: 1300px; height: 400px;\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"carousel-item\">\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                    <img alt=\"image5\" style=\"width: 1300px; height: 400px;\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a class=\"carousel-control-prev\" href=\"#demo\" data-slide=\"prev\">\r\n");
      out.write("            <span class=\"carousel-control-prev-icon\"></span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"carousel-control-next\" href=\"#demo\" data-slide=\"next\">\r\n");
      out.write("            <span class=\"carousel-control-next-icon\"></span>\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"FundingCategoryContainer\">\r\n");
      out.write("        <div class=\"FundingCategoryList\">\r\n");
      out.write("            <div class=\"FundingCategoryListWrap\">\r\n");
      out.write("                <a class=\"FundingCategoryList\" href=\"#\">\r\n");
      out.write("                     <span class=\"FundingCategoryListCricle\">\r\n");
      out.write("                         <span class=\"FundingCategoryListCricleImage0\"></span>\r\n");
      out.write("                         <span class=\"FundingCategoryListCricleName\">전체보기</span>\r\n");
      out.write("                     </span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a class=\"FundingCategoryList\" href=\"#1\">\r\n");
      out.write("                    <span class=\"FundingCategoryListCricle\">\r\n");
      out.write("                        <span class=\"FundingCategoryListCricleImage1\"></span>\r\n");
      out.write("                        <span class=\"FundingCategoryListCricleName\">테크·가전</span>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a class=\"FundingCategoryList\" href=\"#\">\r\n");
      out.write("                    <span class=\"FundingCategoryListCricle\">\r\n");
      out.write("                        <span class=\"FundingCategoryListCricleImage2\"></span>\r\n");
      out.write("                        <span class=\"FundingCategoryListCricleName\">푸드</span>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a class=\"FundingCategoryList\" href=\"#\">\r\n");
      out.write("                    <span class=\"FundingCategoryListCricle\">\r\n");
      out.write("                        <span class=\"FundingCategoryListCricleImage3\"></span>\r\n");
      out.write("                        <span class=\"FundingCategoryListCricleName\">여행</span>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a class=\"FundingCategoryList\" href=\"#\">\r\n");
      out.write("                    <span class=\"FundingCategoryListCricle\">\r\n");
      out.write("                        <span class=\"FundingCategoryListCricleImage4\"></span>\r\n");
      out.write("                        <span class=\"FundingCategoryListCricleName\">스포츠</span>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a class=\"FundingCategoryList\" href=\"#\">\r\n");
      out.write("                    <span class=\"FundingCategoryListCricle\">\r\n");
      out.write("                        <span class=\"FundingCategoryListCricleImage5\"></span>\r\n");
      out.write("                        <span class=\"FundingCategoryListCricleName\">게임·취미</span>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a class=\"FundingCategoryList\" href=\"#\">\r\n");
      out.write("                    <span class=\"FundingCategoryListCricle\">\r\n");
      out.write("                        <span class=\"FundingCategoryListCricleImage6\"></span>\r\n");
      out.write("                        <span class=\"FundingCategoryListCricleName\">모임</span>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a class=\"FundingCategoryList\" href=\"#\">\r\n");
      out.write("                    <span class=\"FundingCategoryListCricle\">\r\n");
      out.write("                        <span class=\"FundingCategoryListCricleImage7\"></span>\r\n");
      out.write("                        <span class=\"FundingCategoryListCricleName\">반려동물</span>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a class=\"FundingCategoryList\" href=\"#\">\r\n");
      out.write("                    <span class=\"FundingCategoryListCricle\">\r\n");
      out.write("                        <span class=\"FundingCategoryListCricleImage8\"></span>\r\n");
      out.write("                        <span class=\"FundingCategoryListCricleName\">기부후원</span>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"FundingProjectList\">\r\n");
      out.write("        <div class=\"FundingProjectListHead\">\r\n");
      out.write("            <h3 class=\"FundingProjectListHeadTitle\">전체보기</h3>\r\n");
      out.write("            <form class=\"FundingProjectListSearch\">\r\n");
      out.write("                <label for=\"\">\r\n");
      out.write("                    <input type=\"search\" placeholder=\"검색\">\r\n");
      out.write("                    <div class=\"SearchButtonIcon\">\r\n");
      out.write("                        <input type=\"submit\" class=\"SearchButton\" value=\"검색\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </label>\r\n");
      out.write("            </form>\r\n");
      out.write("            <div class=\"FundingProjectListSearchOption1\">\r\n");
      out.write("                전체\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"FundingProjectListSearchOption2\">\r\n");
      out.write("                추천순\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 목록 -->\r\n");
      out.write("        <div class=\"FundingProjectCardList\">\r\n");
      out.write("            <div class=\"FundingProjectCardListIn\">\r\n");
      out.write("                <!-- 목록 제목 -->\r\n");
      out.write("                <div class=\"FundingProjectCardItem\">\r\n");
      out.write("                    <a href=\"#\" class=\"FundingProjectCardItemImageArea\">\r\n");
      out.write("                        <div class=\"FundingProjectCardItemImage\"></div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"FundingProjectCardListInfo\">\r\n");
      out.write("                        <div class=\"FundingProjectCardItemTitle\">\r\n");
      out.write("                            <div class=\"FundingProjectCardItemTitleBox\">\r\n");
      out.write("                                <a class=\"FundingProjectCardItemTitleLink\" href=\"#\">\r\n");
      out.write("                                    <p><strong>가전제품의 놀라움!!!!</strong></p>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <span class=\"RewordProjectCardCategory\">테크·가전</span>\r\n");
      out.write("                                    <span class=\"RewordProjectCardMakerName\">\r\n");
      out.write("                                        주연테크(?)\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"RewordProjectCardBar\">\r\n");
      out.write("                                <span style=\"width: 20%;\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <span class=\"RewordProjectCardPercent\">20%</span>\r\n");
      out.write("                            <span class=\"RewordProjectCardAmount\">10,000,000원</span>\r\n");
      out.write("                            <span class=\"RewordProjectCardDay\">24일 남음</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"FundingProjectCardItem\">\r\n");
      out.write("                    <a href=\"#\" class=\"FundingProjectCardItemImageArea\">\r\n");
      out.write("                        <div class=\"FundingProjectCardItemImage\"></div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"FundingProjectCardListInfo\">\r\n");
      out.write("                        <div class=\"FundingProjectCardItemTitle\">\r\n");
      out.write("                            <div class=\"FundingProjectCardItemTitleBox\">\r\n");
      out.write("                                <a class=\"FundingProjectCardItemTitleLink\" href=\"#\">\r\n");
      out.write("                                    <p><strong>가전제품의 놀라움!!!!</strong></p>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <span class=\"RewordProjectCardCategory\">테크·가전</span>\r\n");
      out.write("                                    <span class=\"RewordProjectCardMakerName\">\r\n");
      out.write("                                        주연테크(?)\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"RewordProjectCardBar\">\r\n");
      out.write("                                <span style=\"width: 20%;\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <span class=\"RewordProjectCardPercent\">20%</span>\r\n");
      out.write("                            <span class=\"RewordProjectCardAmount\">10,000,000원</span>\r\n");
      out.write("                            <span class=\"RewordProjectCardDay\">24일 남음</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"FundingProjectCardItem\">\r\n");
      out.write("                    <a href=\"#\" class=\"FundingProjectCardItemImageArea\">\r\n");
      out.write("                        <div class=\"FundingProjectCardItemImage\"></div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"FundingProjectCardListInfo\">\r\n");
      out.write("                        <div class=\"FundingProjectCardItemTitle\">\r\n");
      out.write("                            <div class=\"FundingProjectCardItemTitleBox\">\r\n");
      out.write("                                <a class=\"FundingProjectCardItemTitleLink\" href=\"#\">\r\n");
      out.write("                                    <p><strong>가전제품의 놀라움!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!</strong></p>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <span class=\"RewordProjectCardCategory\">테크·가전</span>\r\n");
      out.write("                                    <span class=\"RewordProjectCardMakerName\">\r\n");
      out.write("                                        주연테크(?)\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"RewordProjectCardBar\">\r\n");
      out.write("                                <span style=\"width: 20%;\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <span class=\"RewordProjectCardPercent\">20%</span>\r\n");
      out.write("                            <span class=\"RewordProjectCardAmount\">10,000,000원</span>\r\n");
      out.write("                            <span class=\"RewordProjectCardDay\">24일 남음</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"FundingProjectCardItem\">\r\n");
      out.write("                    <a href=\"#\" class=\"FundingProjectCardItemImageArea\">\r\n");
      out.write("                        <div class=\"FundingProjectCardItemImage\"></div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"FundingProjectCardListInfo\">\r\n");
      out.write("                        <div class=\"FundingProjectCardItemTitle\">\r\n");
      out.write("                            <div class=\"FundingProjectCardItemTitleBox\">\r\n");
      out.write("                                <a class=\"FundingProjectCardItemTitleLink\" href=\"#\">\r\n");
      out.write("                                    <p><strong>가전제품의 놀라움!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!</strong></p>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <span class=\"RewordProjectCardCategory\">테크·가전</span>\r\n");
      out.write("                                    <span class=\"RewordProjectCardMakerName\">\r\n");
      out.write("                                        주연테크(?)\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"RewordProjectCardBar\">\r\n");
      out.write("                                <span style=\"width: 20%;\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <span class=\"RewordProjectCardPercent\">20%</span>\r\n");
      out.write("                            <span class=\"RewordProjectCardAmount\">10,000,000원</span>\r\n");
      out.write("                            <span class=\"RewordProjectCardDay\">24일 남음</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("            <div class=\"MoreFunding\">\r\n");
      out.write("                <button id=\"moreBtn\">더보기↓</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
