/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.44
 * Generated at: 2021-06-08 09:57:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.funding;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ready2Charge_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/makerNav.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Choice Charge | IF Maker Studio", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    ul.listCheckMark{\r\n");
      out.write("        list-style-image: url( \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/checked.png\" );\r\n");
      out.write("       \r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("    }\r\n");
      out.write("    div.cardTag{\r\n");
      out.write("        border-radius: 10px 0px 0px 14px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .makeLikebutton{\r\n");
      out.write("        opacity: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* 선택시 선택완료라고 변경하기 */\r\n");
      out.write("    input[type=radio]:checked +label{\r\n");
      out.write("\r\n");
      out.write("        background-color: darkcyan;\r\n");
      out.write("        color: white;\r\n");
      out.write("        content: '선택 완료';\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<!-- 요금제 코드 사용 rate_plan_code -->\r\n");
      out.write("    <div class=\"container p-5\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"hide_funding_no\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${funding_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("        <h1 class=\"font-weight-bold\"> 요금제 선택</h1>\r\n");
      out.write("        <p class=\"text-muted\">원하는 요금제를 선택해주세요</p>\r\n");
      out.write("\r\n");
      out.write("        <div class= \"bg-light rounded p-3\" style=\"height: 100px;\">\r\n");
      out.write("            <p class=\"font-weight-bold\">\r\n");
      out.write("                전체 서비스별 안내가 필요하신가요?\r\n");
      out.write("            </p>\r\n");
      out.write("            <a href=\"\">\r\n");
      out.write("                <p class=\"text-info\">메이커 서비스 보러가기</p>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"lightcard d-flex container\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"cardTag border p-4 bg-info\" style=\"width: 12rem;\">\r\n");
      out.write("                <h5 class=\"font-weight-bold\">Light</h5>\r\n");
      out.write("                <h6 class=\"mb-2\">수수료 9%</h6>\r\n");
      out.write("                <p>(VAT 별도)</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"p-4 border\" style=\"width: 45rem;\">\r\n");
      out.write("                <span class=\"h6 mb-2 text-muted\">가볍게 펀딩을 시작하고 싶다면</span>\r\n");
      out.write("                <input id=\"LightCharge\" value =\"light\" type=\"radio\" name=\"choiceCharge\" class=\"makeLikebutton\" />\r\n");
      out.write("                <label class=\"d-inline-flex float-right btn btn-outline-info \" for=\"LightCharge\">선택하기</label>\r\n");
      out.write("                \r\n");
      out.write("                <br><br><br>\r\n");
      out.write("                <div class=\"card-text\">\r\n");
      out.write("                    <ul class=\"listCheckMark\">\r\n");
      out.write("                        <li>펀딩 오픈</li>\r\n");
      out.write("                        <li>이프 스쿨 수강</li>\r\n");
      out.write("                        <li>컨텐츠 제작 도우미</li>\r\n");
      out.write("                        <li>이딜리버리</li>\r\n");
      out.write("                        <li>데이터 플러스 (BETA)</li>\r\n");
      out.write("                        <li>새소식 알림</li>\r\n");
      out.write("                        <li>펀딩 인증마크</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"basiccard d-flex container\">\r\n");
      out.write("            <div class=\"cardTag border p-4 bg-success\" style=\"width: 12rem;\">\r\n");
      out.write("                <h5 class=\"font-weight-bold\">Basic</h5>\r\n");
      out.write("                <h6 class=\"mb-2\">수수료 12%</h6>\r\n");
      out.write("                <p>(VAT 별도)</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"p-4 border\" style=\"width: 45rem;\">\r\n");
      out.write("                \r\n");
      out.write("                <span class=\"h6 mb-2 text-muted\">펀딩을 미리 오픈해서\r\n");
      out.write("                        사전에 서포터를 모으고 싶다면</span>\r\n");
      out.write("                <input id=\"BasicCharge\" value =\"basic\" type=\"radio\" name=\"choiceCharge\" class=\"makeLikebutton\" />\r\n");
      out.write("                <label class=\"d-inline-flex float-right btn btn-outline-info \" for=\"BasicCharge\">선택하기</label>\r\n");
      out.write("                \r\n");
      out.write("                <br><br><br>\r\n");
      out.write("                <div class=\"card-text\">\r\n");
      out.write("                    <h6 class=\"font-weight-bold\">Light 요금제의 모든 서비스 포함 +</h6>\r\n");
      out.write("                    <ul class=\"listCheckMark\">\r\n");
      out.write("                        <li>📣 오픈예정 서비스</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("                \r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"Pro d-flex container\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"cardTag border p-4 bg-danger\" style=\"width: 12rem;\">\r\n");
      out.write("                <h5 class=\"font-weight-bold text-light\">Pro</h5>\r\n");
      out.write("                <h6 class=\"mb-2 text-light\">수수료 14%</h6>\r\n");
      out.write("                <p class=\"text-light\">(VAT 별도)</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"p-4 border\" style=\"width: 45rem;\">\r\n");
      out.write("                <span class=\"h6 mb-2 text-muted\">온・오프라인에서\r\n");
      out.write("                        동시에 서포터를 모으고 싶다면</span>\r\n");
      out.write("                <input id=\"ProCharge\" value =\"pro\" type=\"radio\" name=\"choiceCharge\" class=\"makeLikebutton\" />\r\n");
      out.write("                <label class=\"d-inline-flex float-right btn btn-outline-info \" for=\"ProCharge\">선택하기</label>\r\n");
      out.write("                \r\n");
      out.write("                <br><br><br>\r\n");
      out.write("                <div class=\"card-text\">\r\n");
      out.write("                    <h6 class=\"font-weight-bold\">Light 요금제의 모든 서비스 포함 +</h6>\r\n");
      out.write("                    <ul class=\"listCheckMark\">\r\n");
      out.write("                        <li>📣 오픈예정 서비스</li>\r\n");
      out.write("                        <li>✨ 공간 이프 쇼룸</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("                \r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"Expert d-flex container\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"cardTag border p-4 bg-dark\" style=\"width: 12rem;\">\r\n");
      out.write("                <h5 class=\"font-weight-bold text-white\">Expert</h5>\r\n");
      out.write("                <h6 class=\"mb-2 text-light\">수수료 별도 협의</h6>\r\n");
      out.write("                <p class=\"text-light\">(VAT 별도)</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"p-4 border\" style=\"width: 45rem;\">\r\n");
      out.write("                <span class=\"h6 mb-2 text-muted\">\r\n");
      out.write("                    성공적인 펀딩을 위해\r\n");
      out.write("                    와디즈 담당자의 도움을 받고싶다면\r\n");
      out.write("                </span>\r\n");
      out.write("\r\n");
      out.write("                <input id=\"ExpertCharge\" value =\"expert\" type=\"radio\" name=\"choiceCharge\" class=\"makeLikebutton\" />\r\n");
      out.write("                <label class=\"d-inline-flex float-right btn btn-outline-info \" for=\"ExpertCharge\">선택하기</label>\r\n");
      out.write("                \r\n");
      out.write("                <br><br><br>\r\n");
      out.write("                <div class=\"card-text\">\r\n");
      out.write("                    <h6 class=\"font-weight-bold\">Light 요금제의 모든 서비스 포함 +</h6>\r\n");
      out.write("                    <ul class=\"listCheckMark\">\r\n");
      out.write("                        <li>📣 오픈예정 서비스</li>\r\n");
      out.write("                        <li>✨ 공간 이프 쇼룸</li>\r\n");
      out.write("                        <li>🔊 광고대행 중개 서비스</li>\r\n");
      out.write("                        <li>👨‍💻 PD 컨설팅</li>\r\n");
      out.write("                        <li>📝 에디터 피드백</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("                \r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("\r\n");
      out.write("        <button type=\"button\" onclick=\"saveCharge()\" class=\"btn btn-primary btn-lg m-3\" style=\"width: 200px;\">저장하기</button>\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("                \r\n");
      out.write("</section>   \r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//요금제 저장\r\n");
      out.write("function saveCharge(){\r\n");
      out.write("\r\n");
      out.write("    const charge = $(\"section\").find(\"[name=choiceCharge]:checked\").val();\r\n");
      out.write("    console.log(charge);\r\n");
      out.write("\tconst no = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${funding.funding_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\tconsole.log(no);\r\n");
      out.write("    \r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:`");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/funding/saveCharge/${no}/${charge}`,\r\n");
      out.write("\t\tmethod: \"put\",\r\n");
      out.write("\t\tsuccess(data){\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror: console.log\r\n");
      out.write("\t\t});\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
