/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.44
 * Generated at: 2021-06-09 10:51:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.funding;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ready1Funding_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/makerNav.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("IF Maker Studio", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* 모달 배경화면 투명도  */\r\n");
      out.write(".modal-backdrop\r\n");
      out.write("{\r\n");
      out.write("    opacity:0.5 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 내부 scroll */\r\n");
      out.write("/* Important part */\r\n");
      out.write(".modal-dialog{\r\n");
      out.write("    overflow-y: initial !important\r\n");
      out.write("}\r\n");
      out.write(".modal-body{\r\n");
      out.write("    height: 80vh;\r\n");
      out.write("    overflow-y: auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Modal 처리 -->\r\n");
      out.write("    <div id=\"makerGuide\" class=\"modal\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("        <div class=\"modal-dialog\" role=\"document\" >\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <p class=\"font-weight-bold pt-1\"> 펀딩 서비스 요금제 변경 안내</p>\r\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                    <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <div class=\"modal-body\" data-spy=\"scroll\"  style=\"height: 500px;\">\r\n");
      out.write("                안녕하세요. 와디즈입니다.<br><br>\r\n");
      out.write("                와디즈는 메이커님들의 수수료 부담을 최소화하고, \r\n");
      out.write("                보다 성공적인 펀딩을 위한 다양한 부가 서비스를 자유롭게 선택하실 수 있도록\r\n");
      out.write("                 펀딩 서비스를 개편했습니다.<br><br>\r\n");
      out.write("                 이에 요금제도 개편 예정 (2021년 5월 3일 9시 경 제출 건 부터 적용) 이오니, \r\n");
      out.write("                 자세한 사항은 아래 내용을 참고해 주시길 바랍니다.<br><br>\r\n");
      out.write("                 1. 현재 9.4%인 기본 수수료(중개 수수료 7%, PG 수수료 2.4%)를 9%로 소폭 낮추었습니다.<br>\r\n");
      out.write("                 메이커님들의 수수료 부담이 조금이라도 덜어지길 바랍니다.<br><br>\r\n");
      out.write("                 2. 단일로 제공되던 요금제 유형을 네 가지로 세분화하여 메이커님들의 선택의 폭을 대폭 확대했습니다.<br>\r\n");
      out.write("                 모든 요금제는 PG사 결제 대행 수수료를 포함하고 있으며, 제공되는 서비스에 따라 수수료율이 부과되는 방식입니다.<br><br>\r\n");
      out.write("                 <h3>1) Light 요금제</h3>\r\n");
      out.write("                 <p>Light는 중개 서비스에 PG 수수료를 포함한 요금제입니다. (기존 9.4% → 9.0%)<br>\r\n");
      out.write("                    Light 요금제는 \r\n");
      out.write("                    <span class=\"FundingInfoModal_strong__Qr7rx\">펀딩 오픈</span>\r\n");
      out.write("                    과 메이커가 프로젝트를 진행하고 성공시키는데 도움이 되는 \r\n");
      out.write("                    <span class=\"FundingInfoModal_strong__Qr7rx\">\r\n");
      out.write("                        와디즈 스쿨 수강, 데이터 플러스, 새소식 알림 서비스, 펀딩 인증마크, 제휴 서비스\r\n");
      out.write("                    </span>를 제공합니다.</p><br>\r\n");
      out.write("                    <h3>2) Basic 요금제</h3>\r\n");
      out.write("                    <p>Basic 요금제는 Light 요금제가 제공하는 모든 서비스를 포함하며 \r\n");
      out.write("                        <span class=\"FundingInfoModal_strong__Qr7rx\">추가적으로&nbsp;\r\n");
      out.write("                            <a class=\"FundingInfoModal_underline__lZfZS\" href=\"https://help.wadiz.kr/ko/articles/1540148\">\r\n");
      out.write("                                오픈예정 서비스</a>를 제공</span>합니다. \r\n");
      out.write("                                (기존 12.4% → 12.0%)</p><br>\r\n");
      out.write("                                <h3>3) Pro 요금제</h3>\r\n");
      out.write("                                <p>Pro 요금제는 Basic 요금제가 제공하는 모든 서비스를 포함하며 \r\n");
      out.write("                                    <span class=\"FundingInfoModal_strong__Qr7rx\">추가적으로&nbsp;\r\n");
      out.write("                                        <a class=\"FundingInfoModal_underline__lZfZS\" href=\"https://www.wadiz.kr/link/spacewadiz_info\">\r\n");
      out.write("                                            공간와디즈 쇼룸</a>을 제공</span>합니다. (14%, 신설 요금제)</p><br>\r\n");
      out.write("                                            <h3>4) Expert 요금제</h3>\r\n");
      out.write("                                            <p>Expert 요금제는 Pro 요금제가 제공하는 모든 서비스를 포함하며 추가적으로 광고 대행 서비스, PD 컨설팅, 에디터 피드백을 제공합니다. (별도 협의, 신설 요금제)</p><br>\r\n");
      out.write("                                            3. 적용 일자<br>2021년 5월 3일 09시 이후, 메이커 스튜디오 [제출하기]를 클릭한 건부터 적용<br><br>\r\n");
      out.write("                                            * 상기 수수료에는 VAT가 포함되어 있지 않습니다.<br><br>\r\n");
      out.write("                                            각 서비스에 대한 자세한 안내사항은&nbsp;<a class=\"FundingInfoModal_link__GsFYL\" href=\"https://www.wadiz.kr/link/funding_plan_newsBoard_202104\">공지사항</a>\r\n");
      out.write("                                            을 참고해주시기 바랍니다.<br>\r\n");
      out.write("                                            펀딩 수수료 관련 문의사항은 info@wadiz.kr 로 문의주시면 답변드리겠습니다.\r\n");
      out.write("                                            <br><br>고맙습니다.<br>와디즈 드림<br><br>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer d-flex justify-content-between\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <input type=\"checkbox\" id=\"noSeeWeek\">\r\n");
      out.write("                    <label class=\"text-muted\" for=\"noSeeWeek\">일주일 보지 않기</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button type=\"button\" class=\"border-0 text-info\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container p-5\">\r\n");
      out.write("            <h1 class=\"font-weight-bold\"> 펀딩 준비</h1>\r\n");
      out.write("            <p class=\"lead\">본격적으로 펀딩을 오픈하기 위해 프로젝트에 대한 필수항목을 작성하세요.</p>\r\n");
      out.write("            <!-- 가이드 링크 -->\r\n");
      out.write("            <a href=\"\">\r\n");
      out.write("                <div class=\"p-3 mb-2 bg-info text-white rounded\">리워드 펀딩을 준비하는 메이커님을 위한 <h3>필수 가이드</h3></div>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"border border-secondary\">\r\n");
      out.write("                프로젝트 준비 상태\r\n");
      out.write("                <p class=\"text-right\">\r\n");
      out.write("                    지금 나의 단계는?\r\n");
      out.write("                </p> \r\n");
      out.write("                <p>\r\n");
      out.write("\r\n");
      out.write("                    펀딩 준비 작성 중\r\n");
      out.write("                    필수 항목을 모두 작성 후 저장하기 버튼을 클릭해주세요. 작성 중 > 작성 완료 상태로 변경되어야 최종 제출이 가능합니다.\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"border rounded p-3 \">\r\n");
      out.write("                <br>\r\n");
      out.write("                <p class=\"h3 d-inline\"> 요금제 선택 </p> &nbsp;&nbsp; \r\n");
      out.write("                <!-- 작성 완료하면 작성 완료로 변경 -->\r\n");
      out.write("                <span class=\"d-inline\">작성 전</span> \r\n");
      out.write("                <button type=\"button\" class=\" btn btn-outline-secondary btn-lg float-right\" onclick=\"makerMovePage('2Charge')\">\r\n");
      out.write("                    작성하기\r\n");
      out.write("                </button>\r\n");
      out.write("                <br>\r\n");
      out.write("                <br>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"border rounded p-3\">\r\n");
      out.write("                <br>\r\n");
      out.write("                <p class=\"h3 d-inline\">기본 정보</p> &nbsp;&nbsp; \r\n");
      out.write("                <span class=\"d-inline\">작성 전</span> \r\n");
      out.write("                <button type=\"button\" class=\" btn btn-outline-secondary btn-lg float-right\" onclick=\"makerMovePage('3BasicInfo')\">\r\n");
      out.write("                    작성하기\r\n");
      out.write("                </button>\r\n");
      out.write("                <br>\r\n");
      out.write("                <br>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"border rounded p-3\">\r\n");
      out.write("                <br>\r\n");
      out.write("                <p class=\"h3 d-inline\">스토리 작성</p> &nbsp;&nbsp; \r\n");
      out.write("                <span class=\"d-inline\">작성 전</span> \r\n");
      out.write("                <button type=\"button\" class=\" btn btn-outline-secondary btn-lg float-right\" onclick=\"makerMovePage('4Story')\">\r\n");
      out.write("                    작성하기\r\n");
      out.write("                </button>\r\n");
      out.write("                <br>\r\n");
      out.write("                <br>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"border rounded p-3\">\r\n");
      out.write("                <br>\r\n");
      out.write("                <p class=\"h3 d-inline\">리워드 설계</p> &nbsp;&nbsp; \r\n");
      out.write("                <span class=\"d-inline\">작성 전</span> \r\n");
      out.write("                <button type=\"button\" class=\" btn btn-outline-secondary btn-lg float-right\" onclick=\"makerMovePage('5Reward')\">\r\n");
      out.write("                    작성하기\r\n");
      out.write("                </button>\r\n");
      out.write("                <br>\r\n");
      out.write("                <br>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t <div class=\"border rounded p-3\">\r\n");
      out.write("                <br>\r\n");
      out.write("                <p class=\"h3 d-inline\">관리</p> &nbsp;&nbsp; \r\n");
      out.write("                <span class=\"d-inline\">작성 전</span> \r\n");
      out.write("                <button type=\"button\" class=\" btn btn-outline-secondary btn-lg float-right\" onclick=\"makerMovePage('6Reward')\">\r\n");
      out.write("                    작성하기\r\n");
      out.write("                </button>\r\n");
      out.write("                <br>\r\n");
      out.write("                <br>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        </section>\r\n");
      out.write("<script>\r\n");
      out.write("    //팝업 페이지\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("        $(\"#makerGuide\").modal()\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    //클릭시 페이지 이동\r\n");
      out.write("    function makerMovePage(pagename){\r\n");
      out.write("        location.href=`");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/funding/ready${pagename}`;\r\n");
      out.write("    };\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
