/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.44
 * Generated at: 2021-06-09 15:08:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.funding;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import java.util.Date;

public final class ready5Reward_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/makerNav.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Reward | IF Maker Studio", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* 모달 배경화면 투명도  */\r\n");
      out.write(".modal-backdrop\r\n");
      out.write("{\r\n");
      out.write("    opacity:0.5 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 내부 scroll */\r\n");
      out.write("/* Important part */\r\n");
      out.write(".modal-dialog{\r\n");
      out.write("    overflow-y: initial !important\r\n");
      out.write("}\r\n");
      out.write(".modal-body{\r\n");
      out.write("    height: 80vh;\r\n");
      out.write("    overflow-y: auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");

	Date nowTime = new Date();
	SimpleDateFormat sf = new SimpleDateFormat("yyyy/MM");

      out.write("\r\n");
      out.write("    <div class=\"container p-5\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!--후에 funding_no로 바꿔줄것 -->\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"funding_no\" value=\"17\" /> <br>\r\n");
      out.write("\r\n");
      out.write("        <h1 class=\"font-weight-bold\">리워드 설계</h1>\r\n");
      out.write("        <p>서포터에게 제공할 리워드 내용을 입력하세요. 서포터가 쉽게 펀딩할 수 있는 저렴한 리워드부터 서포터의 보다 빠른 펀딩을 유도할 수 있는 얼리버드 리워드까지 다양한 리워드를 구성하세요.</p>\r\n");
      out.write("        <br>\r\n");
      out.write("        <div class=\"border p-3\">\r\n");
      out.write("            <p class=\"font-weight-bold pt-3 pb-1\">리워드 설계 조건</p>\r\n");
      out.write("            <table>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td class=\"pt-2\">\r\n");
      out.write("                        <p class=\"text-muted font-weight-bold\">정렬 순서</p>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td class=\"pl-5\">\r\n");
      out.write("                        <p class=\"text-muted \">\r\n");
      out.write("                            혜택이 높은 순으로 나오도록 정렬 순서를 등록하세요.\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <p class=\"text-muted font-weight-bold\">제한 수량</p>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td class=\"pl-5\">\r\n");
      out.write("                        <p class=\"text-muted \">\r\n");
      out.write("                            생산 및 제공할 수 있는 리워드의 총 수량으로 해당 수량이 모두 펀딩되면 더 이상 펀딩 불가합니다\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <p class=\"text-muted font-weight-bold\">발송 시작일</p> \r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td class=\"pl-5\">\r\n");
      out.write("                        <p class=\"text-muted \">\r\n");
      out.write("                            프로젝트 종료일 이후부터 11개월 이내로 설계 가능합니다.\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td class=\"pl-5\">\r\n");
      out.write("                        <div class=\"bg-light text-muted\">\r\n");
      out.write("                            ※ 설정한 발송 시작일까지 리워드가 발송되지 않을 경우, 서포터가 펀딩금 반환을 신청할 수 있으니 신중하게 선택하세요.\r\n");
      out.write("                            <br>\r\n");
      out.write("                            ※ 종료일+11개월까지 발송이 시작되지 않은 경우, 미발송 상태인 서포터의 펀딩금 반환이 자동으로 반환(결제취소)되니 유의하세요.\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <br>\r\n");
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <p class=\"text-muted font-weight-bold\">옵션 조건\r\n");
      out.write("                        </p> \r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td class=\"pl-5\">\r\n");
      out.write("                        <p class=\"text-muted \">\r\n");
      out.write("                            옵션(사이즈, 색상 등)이 필요한 경우, 옵션을 추가하세요.리워드 옵션 2개 이상 설계 방법 알아보기\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("        <button type=\"button\" onclick=\"makerRewardAdd()\" class=\"btn btn-secondary\" onclick=\"rewardAddModal()\">\r\n");
      out.write("            +추가하기\r\n");
      out.write("        </button>\r\n");
      out.write("        <br>\r\n");
      out.write("\r\n");
      out.write("        <!-- insert Modal 처리 -->\r\n");
      out.write("        <div id=\"makerRewardInsert\" class=\"modal\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("            <div class=\"modal-dialog\" role=\"document\" >\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("            <form name=\"rewardInsertFrm\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/markerFuning/insertReward.do\" method=\"post\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <p class=\"font-weight-bold\">리워드 추가</p>\r\n");
      out.write("                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                        <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <hr>\r\n");
      out.write("                <div class=\"modal-body\" data-spy=\"scroll\"  style=\"height:70vh;\">\r\n");
      out.write("                    \r\n");
      out.write("                    <br>    \r\n");
      out.write("                    <h6 class=\"font-weight-bold\"> 금액</h6>\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <input type=\"number\" min =\"1000\" max=\"100000000\"  class=\"form-control\" placeholder=\"목표 금액 입력\" aria-label=\"Recipient's username\" aria-describedby=\"basic-addon2\">\r\n");
      out.write("                        <span class=\"p-1\">원</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <br>    \r\n");
      out.write("                    <h6 class=\"font-weight-bold\">리워드명</h6>\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <textarea id=\"rewardName\" type=\"text\" class=\"form-control\" maxlength=\"40\" placeholder=\"타이틀 입력 ex)[얼리버드]기본 리워드\"  rows=\"1\" aria-label=\"Recipient's username\" aria-describedby=\"basic-addon2\"></textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p id=\"rewardName_cnt\" class=\"text-muted ml-1\" style=\"font-size: 12px\">60자 남음</p>\r\n");
      out.write("\r\n");
      out.write("                    <h6 class=\"font-weight-bold\">상세설명</h6>\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <textarea id=\"describe\" class=\"form-control\" aria-label=\"With textarea\" id=\"basicRequireYes\" placeholder=\"제공하는 리워드가 무엇인지 간략하게 제시해 주세요.\" cols=\"\"  rows=\"3\" maxlength=\"400\"></textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("                        <!-- 몇 글자 남았는지 표시 -->\r\n");
      out.write("                        <p id=\"describe_cnt\" class=\"text-muted ml-1\" style=\"font-size: 12px\">400자 남음</p>\r\n");
      out.write("                    \r\n");
      out.write("                    <br>\r\n");
      out.write("                    <h6>옵션조건</h6>\r\n");
      out.write("                    <div class=\"input-group mb-3\">\r\n");
      out.write("                        <select class=\"custom-select\" id=\"makerCategory\">\r\n");
      out.write("                            <option selected disabled>옵션 조건 유형을 선택하세요</option>\r\n");
      out.write("                            <option value=\"optionNon\">옵션 없음</option>\r\n");
      out.write("                            <option value=\"optionChoice\">선택 옵션(사이즈, 색상 등)</option>\r\n");
      out.write("                            <option value=\"optionDirect\">직접 입력 옵션(각인,메시지 등)</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- 선택옵션일 경우 -->\r\n");
      out.write("                    <div id=\"optionChoice\">\r\n");
      out.write("                        <p class=\"text-muted\">옵션 설정</p>\r\n");
      out.write("                        <textarea class=\"form-control\" aria-label=\"With textarea\" id=\"basicRequireYes\" placeholder=\"옵션 값을 입력하세요. &#13;&#10;옵션값은 엔터로 구분됩니다.&#13;&#10; 예시:블랙,230mm &#13;&#10;         화이트, 240mm\" cols=\"\"  rows=\"5\"></textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- 직접 입력 옵션(각인, 메시지등)일 경우 -->\r\n");
      out.write("                    <div id=\"optionDirect\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"옵션 안내 메시지 입력\" aria-label=\"Recipient's username\" aria-describedby=\"basic-addon2\">\r\n");
      out.write("                        <p class=\"text-muted\">예시)한글 10자, 영문 15자 이내 각인 메시지를 입력하세요</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <h6>배송조건</h6>\r\n");
      out.write("                    <div class=\"makerRewardShipPrice ml-1\">\r\n");
      out.write("                    \t<div class=\"custom-control custom-radio\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" name=\"shipPriceYN\" id=\"shipNeed\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"custom-control-input\"  onchange=\"showShipPrice()\" checked> \r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"custom-control-label\" for=\"shipNeed\">배송이 필요한 리워드 입니다.</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t    <!-- 배송이 필요한 리워드 일때만 보일 것 -->\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("                        <div id=\"shipPrice\" class=\"input-group\">\r\n");
      out.write("                            <label class=\"p-1 ml-4\">배송료&nbsp;</label>\r\n");
      out.write("                            <div>\r\n");
      out.write("\t                            <input type=\"text\" style=\"width:100px\" class=\"border rounded\" value=\"0\" aria-label=\"Recipient's username\" aria-describedby=\"basic-addon2\">\r\n");
      out.write("                            \t<span class=\"p-1\">원</span>\r\n");
      out.write("                                <p class=\"text-muted\" style=\"font-size: 12px\">(배송비가 없는 경우,0원 입력)</p>\r\n");
      out.write("                            </div>                            \r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"custom-control custom-radio\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" name=\"shipPriceYN\" id=\"scheduled\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"custom-control-input\" onchange=\"showShipPrice()\"> <label\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"custom-control-label\" for=\"scheduled\">배송이 필요 없는 리워드입니다.</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <br>    \r\n");
      out.write("                    <h6 class=\"font-weight-bold\">제한수량</h6>\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" maxlength=\"40\" placeholder=\"수량 입력\" aria-label=\"Recipient's username\" aria-describedby=\"basic-addon2\">\r\n");
      out.write("                        <span class=\"p-1\">개</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <br>\r\n");
      out.write("                    <h6 class=\"font-weight-bold\">발송시작일</h6>\r\n");
      out.write("                    <div class=\"input-group-prepend\">\r\n");
      out.write("                    <select class=\"form-control\" aria-label=\".form-select-sm example\">\r\n");
      out.write("                        <option selected class=\"text-muted\" disabled>연도/월</option>\r\n");
      out.write("                        <!-- 동적으로 12개월 불러오기 -->\r\n");
      out.write("                        <option value=\"1\">");
      out.print(nowTime.setDate(nowTime.getMonth()+1));
      out.write("</option>\r\n");
      out.write("                 \t\t<option value=\"2\">");
      out.print(sf.format(nowTime));
      out.write("</option>\r\n");
      out.write("                     \t\r\n");
      out.write("                        <!-- 이어서 -->\r\n");
      out.write("                    </select>\r\n");
      out.write("                    &nbsp;\r\n");
      out.write("                    <select class=\"form-control\" aria-label=\".form-select-sm example\">\r\n");
      out.write("                        <option selected class=\"text-muted\" disabled>시기</option>\r\n");
      out.write("                        <option value=\"1\">초(1~10일)</option>\r\n");
      out.write("                        <option value=\"2\">중순(11~20일)</option>\r\n");
      out.write("                        <option value=\"3\">말(21~말일)</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <br><br />\r\n");
      out.write("                    <p class=\"text-muted\" style=\"font-size: 12px\">\r\n");
      out.write("\t                    ※ 설정한 발송 시작일까지 리워드가 발송되지 않을 경우, 서포터가 펀딩금 반환을 신청할 수 있으니 신중하게 선택하세요.\r\n");
      out.write("\t                   \t<br /><br />\r\n");
      out.write("\t                    <!-- 종료일 동적으로 설정하기 -->\r\n");
      out.write("\t                    ※ 종료일+11개월(<strong>2022-05-10</strong>)까지 리워드 발송이 시작되지 않은 경우, <strong>2022-05-11</strong>에 미발송 상태인 서포터의 펀딩금 반환이 자동으로 완료 처리(결제 취소)되니 유의하세요\r\n");
      out.write("                    </p>\r\n");
      out.write("                    \r\n");
      out.write("                    <div style=\"text-align:center;\">\r\n");
      out.write("                        <input type=\"reset\" value=\"취소\" class=\"d-inline-flex btn btn-outline-primary btn-lg \" onclick=\"cancel()\"/>\r\n");
      out.write("                        &nbsp;&nbsp;\r\n");
      out.write("                        <input type=\"submit\" value=\"등록\" class=\"d-inline-flex btn btn-primary btn-lg\"></input>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("         <!-- update Modal 처리 -->\r\n");
      out.write("         <div id=\"makerRewardUpdate\" class=\"modal\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("            <div class=\"modal-dialog\" role=\"document\" >\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("            <form name=\"rewardUpdateFrm\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/funding/updateReward.do\" method=\"post\">\r\n");
      out.write("                 <div class=\"modal-header\">\r\n");
      out.write("                    <p class=\"font-weight-bold\">리워드 추가</p>\r\n");
      out.write("                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                        <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <hr>\r\n");
      out.write("                <div class=\"modal-body\" data-spy=\"scroll\"  style=\"height: 80vh;\">\r\n");
      out.write("                    \r\n");
      out.write("                    <br>    \r\n");
      out.write("                    <h6 class=\"font-weight-bold\"> 금액</h6>\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <input type=\"number\" min =\"1000\" max=\"100000000\"  class=\"form-control\" placeholder=\"목표 금액 입력\" aria-label=\"Recipient's username\" aria-describedby=\"basic-addon2\">\r\n");
      out.write("                        <span class=\"p-1\">원</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <br>    \r\n");
      out.write("                    <h6 class=\"font-weight-bold\">리워드명</h6>\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <textarea id=\"rewardName\" type=\"text\" class=\"form-control\" maxlength=\"40\" placeholder=\"타이틀 입력 ex)[얼리버드]기본 리워드\"  rows=\"1\" aria-label=\"Recipient's username\" aria-describedby=\"basic-addon2\"></textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p id=\"rewardName_cnt\" class=\"text-muted ml-1\" style=\"font-size: 12px\">60자 남음</p>\r\n");
      out.write("\r\n");
      out.write("                    <h6 class=\"font-weight-bold\">상세설명</h6>\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <textarea id=\"describe\" class=\"form-control\" aria-label=\"With textarea\" id=\"basicRequireYes\" placeholder=\"제공하는 리워드가 무엇인지 간략하게 제시해 주세요.\" cols=\"\"  rows=\"3\" maxlength=\"400\"></textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("                        <!-- 몇 글자 남았는지 표시 -->\r\n");
      out.write("                        <p id=\"describe_cnt\" class=\"text-muted ml-1\" style=\"font-size: 12px\">400자 남음</p>\r\n");
      out.write("                    \r\n");
      out.write("                    <br>\r\n");
      out.write("                    <h6>옵션조건</h6>\r\n");
      out.write("                    <div class=\"input-group mb-3\">\r\n");
      out.write("                        <select class=\"custom-select\" id=\"makerCategory\">\r\n");
      out.write("                            <option selected disabled>옵션 조건 유형을 선택하세요</option>\r\n");
      out.write("                            <option value=\"optionNon\">옵션 없음</option>\r\n");
      out.write("                            <option value=\"optionChoice\">선택 옵션(사이즈, 색상 등)</option>\r\n");
      out.write("                            <option value=\"optionDirect\">직접 입력 옵션(각인,메시지 등)</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- 선택옵션일 경우 -->\r\n");
      out.write("                    <div id=\"optionChoice\">\r\n");
      out.write("                        <p class=\"text-muted\">옵션 설정</p>\r\n");
      out.write("                        <textarea class=\"form-control\" aria-label=\"With textarea\" id=\"basicRequireYes\" placeholder=\"옵션 값을 입력하세요. &#13;&#10;옵션값은 엔터로 구분됩니다.&#13;&#10; 예시:블랙,230mm &#13;&#10;         화이트, 240mm\" cols=\"\"  rows=\"5\"></textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- 직접 입력 옵션(각인, 메시지등)일 경우 -->\r\n");
      out.write("                    <div id=\"optionDirect\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"옵션 안내 메시지 입력\" aria-label=\"Recipient's username\" aria-describedby=\"basic-addon2\">\r\n");
      out.write("                        <p class=\"text-muted\">예시)한글 10자, 영문 15자 이내 각인 메시지를 입력하세요</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <h6>배송조건</h6>\r\n");
      out.write("                    <div class=\"makerRewardShipPrice ml-1\">\r\n");
      out.write("                    \t<div class=\"custom-control custom-radio\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" name=\"shipPriceYN\" id=\"shipNeed\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"custom-control-input\"  onchange=\"showShipPrice()\" checked> \r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"custom-control-label\" for=\"shipNeed\">배송이 필요한 리워드 입니다.</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t    <!-- 배송이 필요한 리워드 일때만 보일 것 -->\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("                        <div id=\"shipPrice\" class=\"input-group\">\r\n");
      out.write("                            <label class=\"p-1 ml-4\">배송료&nbsp;</label>\r\n");
      out.write("                            <div>\r\n");
      out.write("\t                            <input type=\"text\" style=\"width:100px\" class=\"border rounded\" value=\"0\" aria-label=\"Recipient's username\" aria-describedby=\"basic-addon2\">\r\n");
      out.write("                            \t<span class=\"p-1\">원</span>\r\n");
      out.write("                                <p class=\"text-muted\" style=\"font-size: 12px\">(배송비가 없는 경우,0원 입력)</p>\r\n");
      out.write("                            </div>                            \r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"custom-control custom-radio\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" name=\"shipPriceYN\" id=\"scheduled\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"custom-control-input\" onchange=\"showShipPrice()\"> <label\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"custom-control-label\" for=\"scheduled\">배송이 필요 없는 리워드입니다.</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <br>    \r\n");
      out.write("                    <h6 class=\"font-weight-bold\">제한수량</h6>\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" maxlength=\"40\" placeholder=\"수량 입력\" aria-label=\"Recipient's username\" aria-describedby=\"basic-addon2\">\r\n");
      out.write("                        <span class=\"p-1\">개</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <br>\r\n");
      out.write("                    <h6 class=\"font-weight-bold\">발송시작일</h6>\r\n");
      out.write("                    <div class=\"input-group-prepend\">\r\n");
      out.write("                    <select class=\"form-control\" aria-label=\".form-select-sm example\">\r\n");
      out.write("                        <option selected class=\"text-muted\" disabled>연도/월</option>\r\n");
      out.write("                        <!-- 동적으로 12개월 불러오기 -->\r\n");
      out.write("                        <option value=\"1\">2021/06</option>\r\n");
      out.write("                        <option value=\"2\">2021/07</option>\r\n");
      out.write("                        <option value=\"3\">2021/08</option>\r\n");
      out.write("                        <!-- 이어서 -->\r\n");
      out.write("                    </select>\r\n");
      out.write("                    &nbsp;\r\n");
      out.write("                    <select class=\"form-control\" aria-label=\".form-select-sm example\">\r\n");
      out.write("                        <option selected class=\"text-muted\" disabled>시기</option>\r\n");
      out.write("                        <option value=\"1\">초(1~10일)</option>\r\n");
      out.write("                        <option value=\"2\">중순(11~20일)</option>\r\n");
      out.write("                        <option value=\"3\">말(21~말일)</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <br><br />\r\n");
      out.write("                    <p class=\"text-muted\" style=\"font-size: 12px\">\r\n");
      out.write("\t                    ※ 설정한 발송 시작일까지 리워드가 발송되지 않을 경우, 서포터가 펀딩금 반환을 신청할 수 있으니 신중하게 선택하세요.\r\n");
      out.write("\t                   \t<br /><br />\r\n");
      out.write("\t                    <!-- 종료일 동적으로 설정하기 -->\r\n");
      out.write("\t                    ※ 종료일+11개월(<strong>2022-05-10</strong>)까지 리워드 발송이 시작되지 않은 경우, <strong>2022-05-11</strong>에 미발송 상태인 서포터의 펀딩금 반환이 자동으로 완료 처리(결제 취소)되니 유의하세요\r\n");
      out.write("                    </p>\r\n");
      out.write("                    \r\n");
      out.write("                    <div style=\"text-align:center;\">\r\n");
      out.write("                        <input type=\"reset\" value=\"취소\" class=\"d-inline-flex btn btn-outline-primary btn-lg \" onclick=\"cancel()\"/>\r\n");
      out.write("                        &nbsp;&nbsp;\r\n");
      out.write("                        <input type=\"submit\" value=\"등록\" class=\"d-inline-flex btn btn-primary btn-lg\"></input>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- 리워드 추가시 card로 리워드 보이게 하기 -->\r\n");
      out.write("        <div class=\"rewardCardSpace d-flex justify-content-between\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card mt-4\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                        <!-- 가격 불러오기 -->\r\n");
      out.write("                        <h5 class=\"card-title text-muted\">00원</h5>\r\n");
      out.write("                        <!-- 제한 수량 불러오기 -->\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-primary btn-sm\">제한 수량 00개</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    <!-- 리워드 명 불러오기 -->\r\n");
      out.write("                    <h6 class=\"font-weight-bold card-subtitle mb-2 text-muted\">리워드명</h6>\r\n");
      out.write("                    <!-- 상세설명 불러오기  -->\r\n");
      out.write("                    <p class=\"card-text text-muted\">상세설명</p>\r\n");
      out.write("                    <!-- 배송비 불러오기 -->\r\n");
      out.write("                    <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                        <h6 class=\"font-weight-bold text-muted\">배송비</h6>\r\n");
      out.write("                        <h6 class=\"card-subtitle mb-2 text-muted\">00원</h6>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- 리워드 발송 시작일 불러오기 -->\r\n");
      out.write("                    <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                        <h6 class=\"font-weight-bold text-muted\">리워드 발송 시작일</h6>\r\n");
      out.write("                        <h6 class=\"card-subtitle mb-2 text-muted\">0000년 00월 {시기}</h6>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"d-flex justify-content-end\">\r\n");
      out.write("                        <!-- 매개변수로 reward no 넘겨줄것 -->\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-outline-secondary mr-3\" onclick=\"makerRewardUpdate()\">편집</button>\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-outline-secondary\" onclick=\"deleteReward()\">삭제</a></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <br><br>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-primary btn-lg\" style=\"width: 200px;\">저장하기</button>\r\n");
      out.write("\r\n");
      out.write("        <!-- 리워드 삭제 히든 폼 -->\r\n");
      out.write("        <form name =\"deleteRewardHiddenFrm\" id=\"deleteRewardHiddenFrm\"\r\n");
      out.write("            action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/makerFunding/deleteReward.do\" \r\n");
      out.write("            method=\"POST\">\r\n");
      out.write("\t        <input id=\"hidden\" type=\"hidden\" name=\"rewardNo\"/>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</section> \r\n");
      out.write("<script>\r\n");
      out.write("   function makerRewardAdd(){\r\n");
      out.write("        $(\"#makerRewardInsert\").modal()\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    function makerRewardUpdate(no){\r\n");
      out.write("        $(\"#makerRewardUpdate\").modal()\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    // 배송비 선택시 보이게 안보이게 하기\r\n");
      out.write("    function showShipPrice(){\r\n");
      out.write("        if($('input:radio[id=shipNeed]').is(':checked')){\r\n");
      out.write("            $('#shipPrice').show();\r\n");
      out.write("        }else{\r\n");
      out.write("            $('#shipPrice').hide();\r\n");
      out.write("        }\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    //옵션 선택시 보이게 안보이게 하기\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("            //처음에는 둘 다 안보이게\r\n");
      out.write("            $('#optionDirect').hide();\r\n");
      out.write("            $('#optionChoice').hide();\r\n");
      out.write("\r\n");
      out.write("        $('#makerCategory').change(function() {\r\n");
      out.write("\r\n");
      out.write("            var result = $('#makerCategory option:selected').val();\r\n");
      out.write("           \r\n");
      out.write("            if (result == 'optionDirect') {\r\n");
      out.write("                $('#optionDirect').show();\r\n");
      out.write("                $('#optionChoice').hide();\r\n");
      out.write("            }else {\r\n");
      out.write("                $('#optionChoice').show();\r\n");
      out.write("                $('#optionDirect').hide();\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        }); \r\n");
      out.write("        \r\n");
      out.write("\t    //남은 글자 수 표시하기\r\n");
      out.write("        $('#rewardName').on('keyup', function() {\r\n");
      out.write("            $('#rewardName_cnt').html( 60 - $(this).val().length+\"자 남음\");\r\n");
      out.write(" \r\n");
      out.write("            if($(this).val().length > 60) {\r\n");
      out.write("                $(this).val($(this).val().substring(0, 60));\r\n");
      out.write("                \r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        $('#describe').on('keyup', function() {\r\n");
      out.write("            $('#describe_cnt').html(400 - $(this).val().length+\"자 남음\");\r\n");
      out.write(" \r\n");
      out.write("            if($(this).val().length > 400) {\r\n");
      out.write("                $(this).val($(this).val().substring(0, 400));\r\n");
      out.write("                \r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("    }); \r\n");
      out.write("\r\n");
      out.write("    function deleteReward(){\r\n");
      out.write("\t    if(confirm(\"리워드를 정말 삭제하시겠습니까?\")){\r\n");
      out.write("            var $frm = $(document.deleteRewardHiddenFrm);\r\n");
      out.write("            $frm.find(\"[name = rewardNo]\").val(no);\r\n");
      out.write("            $frm.submit();\r\n");
      out.write("\t    }\r\n");
      out.write("\t\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
