/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.44
 * Generated at: 2021-06-07 10:36:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.maker.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class makerNav_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1622798345519L));
    _jspx_dependants.put("jar:file:/C:/Users/rojoo/git/interact_funding/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Users/rojoo/git/interact_funding/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Users/rojoo/git/interact_funding/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\r\n");
      out.write("    <!-- include libraries(jQuery, bootstrap) -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- include summernote css/js -->\r\n");
      out.write("<link\r\n");
      out.write("  href=\"https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css\"\r\n");
      out.write("  rel=\"stylesheet\"\r\n");
      out.write("/>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- collapse -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"//code.jquery.com/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"//maxcdn.bootstrapcdn.com/bootstrap/latest/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function cancel(){\r\n");
      out.write("    //joocheck\r\n");
      out.write("    console.log(\"취소 진행\");\r\n");
      out.write("    location.href=`");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/makerFunding/cancel.do`;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</script>   \r\n");
      out.write(" \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- 상단 바 -->\r\n");
      out.write("    <nav class=\"navbar sticky-top navbar-light bg-light border-bottom\">\r\n");
      out.write("        <!-- 클릭할 시 펀딩 시작 화면으로 넘어간다. -->\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"#\">\r\n");
      out.write("            <img src=\"\" width=\"30\" height=\"30\" alt=\"\">\r\n");
      out.write("        </a>\r\n");
      out.write("        <!-- 이름 여기에 불러올것 -->\r\n");
      out.write("        <div class=\"makerName\"><img src=\"\" width=\"30\" height=\"30\" alt=\"\">00</div>\r\n");
      out.write("        <div>\r\n");
      out.write("            <button type=\"button\" class=\"border-0\">나가기</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"d-flex\">\r\n");
      out.write("    <!-- 좌측 바 -->\r\n");
      out.write("    <div style=\"width: 280px;\">\r\n");
      out.write("    \r\n");
      out.write("        <div class=\"border\">\r\n");
      out.write("            <div style=\"height:200px;\">\r\n");
      out.write("                <h3>\r\n");
      out.write("                    <!-- 프로젝트 진행명 가져오기 -->\r\n");
      out.write("                    00의 \r\n");
      out.write("                    <br>\r\n");
      out.write("                    멋진 프로젝트\r\n");
      out.write("                </h3>\r\n");
      out.write("                <br>\r\n");
      out.write("                프로젝트 번호 \r\n");
      out.write("                <!-- 프로젝트 번호 불러오기 -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <li class=\"navbar-toggle list-group-item \" data-toggle=\"collapse\" data-target=\"#fundingReady\"> 펀딩준비</li>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"collapse navbar-collapse border\" id=\"fundingReady\">\r\n");
      out.write("            <ul class=\"nav navbar-nav\">\r\n");
      out.write("                <li class=\"p-3\"><a href=\"#\">요금제 선택</a></li>\r\n");
      out.write("                <li class=\"p-3\"><a href=\"#\">기본 요건</a></li>\r\n");
      out.write("                <li class=\"p-3\"><a href=\"#\">기본 정보</a></li> \r\n");
      out.write("                <li class=\"p-3\"><a href=\"#\">스토리 작성</a></li> \r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <li class=\"navbar-toggle list-group-item text-muted\" data-toggle=\"collapse\" data-target=\"#myNavbar\">새소식</li>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"collapse navbar-collapse border\" id=\"myNavbar\">\r\n");
      out.write("            <ul class=\"nav navbar-nav\">\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <li class=\"navbar-toggle list-group-item text-muted\" data-toggle=\"collapse\" data-target=\"#myNavbar\">오픈예정 현황</li>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"collapse navbar-collapse border\" id=\"myNavbar\">\r\n");
      out.write("            <ul class=\"nav navbar-nav\">\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <li class=\"navbar-toggle list-group-item text-muted\" data-toggle=\"collapse\" data-target=\"#myNavbar\">펀딩 현황</li>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"collapse navbar-collapse border\" id=\"myNavbar\">\r\n");
      out.write("            <ul class=\"nav navbar-nav\">\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <li class=\"navbar-toggle list-group-item text-muted\" data-toggle=\"collapse\" data-target=\"#myNavbar\">결제 현황</li>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"collapse navbar-collapse border\" id=\"myNavbar\">\r\n");
      out.write("            <ul class=\"nav navbar-nav\">\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <li class=\"navbar-toggle list-group-item text-muted\" data-toggle=\"collapse\" data-target=\"#myNavbar\">펀딩·발송 관리</li>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"collapse navbar-collapse border\" id=\"myNavbar\">\r\n");
      out.write("            <ul class=\"nav navbar-nav\">\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <li class=\"navbar-toggle list-group-item font-weight-bold\" data-toggle=\"collapse\" data-target=\"#myNavbar\">광고 센터</li>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"collapse navbar-collapse border\" id=\"myNavbar\">\r\n");
      out.write("            <ul class=\"nav navbar-nav\">\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <li class=\"navbar-toggle list-group-item font-weight-bold\" data-toggle=\"collapse\" data-target=\"#myNavbar\">수수료 관리</li>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"collapse navbar-collapse border\" id=\"myNavbar\">\r\n");
      out.write("            <ul class=\"nav navbar-nav\">\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <li class=\"navbar-toggle list-group-item font-weight-bold\" data-toggle=\"collapse\" data-target=\"#myNavbar\">자료 및 도움말</li>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"collapse navbar-collapse border\" id=\"myNavbar\">\r\n");
      out.write("            <ul class=\"nav navbar-nav\">\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("     \r\n");
      out.write("    </div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
